### ISSUE TITLE
Which version support for the API, Is this package compitable to v2 version? 

### ISSUE THREAD

**Issue by prashantidealittechno** [PartFire/onfido#1]
My client get mesaage to update the api to version  v2, can you please update your package to makethe user of version v2 API from onfido server. so that users that are using your package can continue using your package, ?

**Comment by carlowens** [comment]
Master is a clone of the official SDK for v1.  We have create not yet created a version for v2.  We have another branch 'partfire' which does use v2 but we are still messing with it.

If you want to use v2, you can simply fork our master repository and update the config to use v2.  The SDK will then use the v2 url.  However obviously the extra  features that exist on v2 on their API won't exist in the SDK.

**Comment by carlowens** [comment]
Actually yes you should be able to use the partfire branch for v2.  I have added the ability on that branch to update applicants (which is for V2), and we have also changed how errors are handled.  We havent got round to documenting it yet.
